name: on-push-main
on:
  push:
    branches:
      - main

jobs:
  migration:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Install vpn
        run: |
          sudo apt-get update && \
          sudo apt install apt-transport-https -y && \
          sudo wget https://swupdate.openvpn.net/repos/openvpn-repo-pkg-key.pub && \
          sudo apt-key add openvpn-repo-pkg-key.pub && \
          sudo wget -O /etc/apt/sources.list.d/openvpn3.list https://swupdate.openvpn.net/community/openvpn3/repos/openvpn3-focal.list && \
          sudo apt update && \
          sudo apt install openvpn3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ap-southeast-1
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Copy vpn client from s3
        run: |
          aws s3 cp s3://med4all-s3-bucket/github-actionovpn .

      - name: Connect to vpn
        id: vpn_connection
        run: sudo openvpn3 session-start --config ./flyway-db.ovpn

      - name: Migration base table
        run: |
          docker run --rm -v ${PWD}/migration:/flyway/sql flyway/flyway -url=${JDBC_PG_URL} \
          -user=$(aws secretsmanager get-secret-value --secret-id prod/med4all/postgres --version-stage AWSCURRENT | jq -r '.SecretString' | jq -r '.username') \
          -password=$(aws secretsmanager get-secret-value --secret-id prod/med4all/postgres --version-stage AWSCURRENT | jq -r '.SecretString' | jq -r '.password') \
          info repair migrate info
        env:
          JDBC_PG_URL: jdbc:postgresql://med4all-aurora-cluster.cluster-cc5cxjz6cnak.ap-southeast-1.rds.amazonaws.com:5432/med4all

      - name: Kill vpn
        if: always()
        run: sudo openvpn3 session-manage --config ./flyway-db.ovpn --disconnect
